### ISSUE TITLE
ImportError: libpng15-7864b8f1.so.15.13.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by zoldaten** [Qengineering/Install-OpenCV-Raspberry-Pi-64-bits#1]
hi, 
i tried rebuild opencv after clean remove on raspberry pi 4 aarch64.
Everything build succesfully but i got this trying import:

```
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.9/site-packages/cv2/__init__.py", line 8, in <module>
    from .cv2 import *
ImportError: libpng15-7864b8f1.so.15.13.0: cannot open shared object file: No such file or directory
```
i built opencv not using virtual env. 
how to fix that ?
may be something with sym links ?

**Comment by Qengineering** [comment]
@zoldaten,

Strange error.
libpng15 isn't installed and used by OpenCV initially.

Please try the following solutions:
https://askubuntu.com/questions/343184/libpng15-so-15-cannot-open-shared-object-file
or if not working
https://stackoverflow.com/questions/62811239/how-correct-the-import-error-of-libpng15-for-cv2resolve
